spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=zygis
spring.datasource.password=password
spring.datasource.initialization-mode=always
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql = true

## SQL scripts
#sql.script.create.payment=insert into payment(amount, currency, debtorIban, creditorIban, paymentType, details, BICCode, \
#  status, cancellationDate, cancellationFee) \
#  values('100.00', 'EUR', 'NL62INGB2067756052', 'NL56RABO1971879746', 'EUR', 'pillow', 'AHBKNL2G', 'ACTIVE', '')


