
CREATE TABLE IF NOT EXISTS public.payment
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9999999 CACHE 1 ),
    amount numeric,
    currency character varying(255),
    debtor_iban character varying(255),
    creditor_iban character varying(255),
    payment_type character varying(255),
    details character varying(255),
    bic_code character varying(255),
    creation_date timestamp without time zone,
    status character varying(255),
    cancellation_date timestamp without time zone,
    cancellation_fee numeric,
    CONSTRAINT payment_key PRIMARY KEY (id)
);

INSERT INTO public.payment (id, amount, currency, debtor_iban, creditor_iban, payment_type, details, bic_code, creation_date, status, cancellation_date, cancellation_fee) VALUES (10, 60, 'USD', 'LT918279381702', 'LT192873918231', 'USD', 'Sports massage', NULL, '2025-05-31 22:07:47.402479', 'active', NULL, NULL);
INSERT INTO public.payment (id, amount, currency, debtor_iban, creditor_iban, payment_type, details, bic_code, creation_date, status, cancellation_date, cancellation_fee) VALUES (11, 15, 'EUR', 'LT8794394873443', 'LT4345345297984', 'EUR', 'Movies', NULL, '2025-05-31 22:09:06.851766', 'active', NULL, NULL);
INSERT INTO public.payment (id, amount, currency, debtor_iban, creditor_iban, payment_type, details, bic_code, creation_date, status, cancellation_date, cancellation_fee) VALUES (12, 55.55, 'USD', 'LT23764234232', 'LT23423423423', 'USD', 'Gym', NULL, '2025-06-02 12:36:40.308743', 'active', NULL, NULL);
INSERT INTO public.payment (id, amount, currency, debtor_iban, creditor_iban, payment_type, details, bic_code, creation_date, status, cancellation_date, cancellation_fee) VALUES (13, 60, 'EUR & USD', 'LT928379428', 'LT192873911', 'EUR & USD', NULL, 'AABALT22', '2025-06-02 13:08:34.738466', 'active', NULL, NULL);

